### ISSUE TITLE
Find suitable template

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/gourbanbus-web#1]

**Comment by russel0907** [comment]
@rosclaritha 

Template 1
https://technext.github.io/mobapp/

Template 2
https://technext.github.io/expert/index.html

Template 3
https://technext.github.io/Lazyfox/

Template 4
https://technext.github.io/kairos/index.html

Template 5
https://technext.github.io/proapp/index.html

**Comment by russel0907** [comment]
@rosclaritha 

template that suits to corporate color style

Template 6
https://prium.github.io/elixir/v3.0.0/

Template 7
https://bootstrapmade.com/demo/NewBiz/

Template 8
https://bootstrapmade.com/demo/Bootslander/

Template 9
https://bootstrapmade.com/demo/Anyar/

Template 10
https://technext.github.io/nexus/index.html

Template 11
https://technext.github.io/imagine/index.html

Template 12
https://demo.themesberg.com/swipe/#testimonials
