### ISSUE TITLE
Change main banner

### ISSUE THREAD

**Issue by paragasu** [phisoft/gourbanbus-web#11]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/180115972-ef72ae04-b7ca-4d21-b954-246db9299529.png">

**Comment by rosclaritha** [comment]
Suggest a few design for the header @russel0907

**Comment by russel0907** [comment]
## Design mockup 1
![Screenshot 2022-07-22 at 10-50-20 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/180352335-8fef7009-1e7e-44b8-b121-5f5af4923f52.png)

## Design mockup 2
![Screenshot 2022-07-22 at 10-40-57 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/180352373-0daf6d20-4ba0-4f68-a0f7-dadc41fcefa1.png)

## Design mockup 3
![Screenshot 2022-07-22 at 10-47-00 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/180352530-9eb1ee12-2aea-4b77-b420-210f41391bd1.png)

##Design mockup 4
![Screenshot 2022-07-22 at 10-31-24 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/180352539-8851871c-0e82-4fee-ac7c-863e6bdfbc56.png)

**Comment by paragasu** [comment]
mockup 1 la

**Comment by russel0907** [comment]
## Hero Section Web view
![Screenshot 2022-07-27 at 13-39-59 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/181171452-3ed063ad-51c3-4614-bb28-7be8818c9f1a.png)

## Hero Section Mobile view
![Screenshot 2022-07-27 at 13-54-16 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/181171722-e5f9ea6b-94db-4bad-9431-6c585e42c6f0.png)
