### ISSUE TITLE
website content features

### ISSUE THREAD

**Issue by paragasu** [phisoft/gourbanbus-web#2]
- [x] tagline
- [x] features - gps tracker

**Comment by elioralatri** [comment]
@paragasu 
Suggested Taglines:
1. Go smoothly, reach safely.
2. Move freely and happily.
3. Urban Transit redefined.
4. Way of Transit excellence
5. Experience a Hassle-free happiness
6. Make moving easy.
7. Efficient. Safe. Reliable.
8. You scan it. We haul you.

GPS tracker
With gourbanbus, you won't have to wait too long to find out where the bus is and how long it will take you to arrive. The GPS tracker allows you to quickly monitor and track the bus's whereabouts within the specified region. It facilitates a seamless and trouble-free transfer from one area to another. As these GPS trackers enable real-time tracking of the bus, passengers and bus drivers are able to observe each other's locations in real-time. Therefore, passengers save time and effort. By determining whether or not a passenger is waiting at the bus stop, the driver may plan their route and save time.
