### ISSUE TITLE
Create logo for gourbanbus

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/gourbanbus-web#21]
Suggest a few designs for the gourbanbus system. You can follow the current theme colour of the website.
![image](https://user-images.githubusercontent.com/30463117/182282147-b6b5ab19-d86d-4425-9075-2273538f6642.png)

**Comment by russel0907** [comment]
@rosclaritha 

## Design 1
![design 1](https://user-images.githubusercontent.com/94702093/182319468-227061b5-3ae8-4a43-87a5-9548c36ea3c7.png)

## Design 2
![d-3](https://user-images.githubusercontent.com/94702093/182319576-57066a7b-ea26-419a-943f-f7eeb12ca607.png)

## Design 3
![d-2](https://user-images.githubusercontent.com/94702093/182319621-12581d8e-783f-4409-985d-9d83aff5d0b1.png)

## Design 4
![d-4](https://user-images.githubusercontent.com/94702093/182319737-eb4d1825-cac6-4101-ac54-572891851689.png)

## Design 5
![d-5](https://user-images.githubusercontent.com/94702093/182319782-bc5e3164-8a4e-426a-ab88-58d0b101ba5d.png)

**Comment by rosclaritha** [comment]
Proceed with Design 5. Provide the design files here.
![image](https://user-images.githubusercontent.com/30463117/182325979-9d2aa98c-8c6d-4454-b24d-65d5c35a301b.png)

**Comment by russel0907** [comment]
@rosclaritha 

Resources;
[logo-gourbanbus.zip](https://github.com/phisoft/gourbanbus-web/files/9240396/logo-gourbanbus.zip)
