### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/gourbanbus-web#23]
Find and suggest others fonts to make the website more appealing.
![image](https://user-images.githubusercontent.com/30463117/182507435-12c5fa8f-b4bf-4295-be68-5cb07e8c20a5.png)

**Comment by russel0907** [comment]
@rosclaritha 
## Font 1 fredoka+comfortaa
![Web 1280 – 1](https://user-images.githubusercontent.com/94702093/182529796-c16cbd57-00fe-47c8-b22c-c498dd2da0d2.png)

## Font 2 Outfit
![Font2](https://user-images.githubusercontent.com/94702093/182530060-76c371bf-552d-460e-bb26-9e17cd3e9c72.png)

## Font 3 Red Hat 
![Font3](https://user-images.githubusercontent.com/94702093/182530207-126b524d-a989-49ab-994c-91f2d0eb2e8b.png)
 
## Font 4
![Font4](https://user-images.githubusercontent.com/94702093/182530351-56a48189-b3da-4fc8-be65-3410cab77158.png)
