### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/gourbanbus-web#3]
Use the following template: https://bootstrapmade.com/demo/Anyar/

**Comment by russel0907** [comment]
**Progress 1**
• Redesign website using the chosen template
• Update contact information

![Web 1920 – 1](https://user-images.githubusercontent.com/94702093/178445495-88aeeb1d-fada-40e2-a11f-9fbf60911699.png)

**Comment by russel0907** [comment]
**Progress 2**

Hero background Image
![Screenshot 2022-07-13 at 11-05-42 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/178642206-2c9c835c-22b9-426c-b187-254a8cee76bb.png)


Content
![Screenshot 2022-07-13 at 11-05-34 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/178642157-91a77721-3096-4a47-990e-c6999fbdfcd5.png)
