### ISSUE TITLE
Update website content

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/gourbanbus-web#6]
Get the content from https://github.com/phisoft/gourbanbus-web/issues/7

**Comment by russel0907** [comment]
Progress

 
## Hero Section
![Screenshot 2022-07-20 at 10-54-43 Gourbanbus Urban Bus System](https://user-images.githubusercontent.com/94702093/179886230-ccad3ce8-5a7c-41bb-9cff-39870330aff6.png)

**Comment by russel0907** [comment]
## About section
![Screenshot (401)](https://user-images.githubusercontent.com/94702093/180124600-cd28adf9-4b94-488d-bfd4-5e70efbbb9ba.png)

## Services Section
![Screenshot (402)](https://user-images.githubusercontent.com/94702093/180124622-e0f40a41-01cb-4bb4-8437-9a73d2696b26.png)

## Benefits section
![Screenshot (403)](https://user-images.githubusercontent.com/94702093/180124643-3c29fdb7-c28a-49bb-a4eb-a64f52e4dd05.png)
